CREATE DATABASE LIBRARY;

USE LIBRARY;

CREATE TABLE BOOK_CATEGORY(
CATEGORY_ID INT PRIMARY KEY,
CATEGORY_NAME VARCHAR(25));

CREATE TABLE BOOK_MASTER(
BOOK_ID INT PRIMARY KEY,
CATEGORY_ID INT,
BOOK_TITLE VARCHAR(25),
AUTHOR VARCHAR(25),
BOOK_PRICE MONEY,
CONSTRAINT FK_BOOK FOREIGN KEY(CATEGORY_ID)
REFERENCES BOOK_CATEGORY(CATEGORY_ID));

CREATE TABLE VISITOR_INFO(
VISITOR_ID INT PRIMARY KEY,
VISITOR_NAME VARCHAR(25),
GENDER VARCHAR(10),
VISITOR_MAIL VARCHAR(25),
VISITOR_CONTACT INT);

CREATE TABLE MEMBER_INFO(
MEMBER_ID INT PRIMARY KEY,
VISITOR_ID INT,
DATE_OF_REGISTRATION DATE,
CAUTION_DEPOSIT MONEY
CONSTRAINT FK_VISITOR_ID FOREIGN KEY(VISITOR_ID)
REFERENCES VISITOR_INFO(VISITOR_ID));

CREATE TABLE TRANSACT(
BOOK_ISSUE_ID INT PRIMARY KEY,
BISSUE_DATE DATE,
BOOK_ID INT,
MEMBER_ID INT,
BOOK_RETURN_DATE DATE,
ACTUAL_RETURN_DATE DATE,
BOOK_RETURN_DELAY INT,
PENALTY MONEY,
CONSTRAINT FK_MEMBERID FOREIGN KEY(MEMBER_ID)
REFERENCES MEMBER_INFO(MEMBER_ID),

CONSTRAINT FK_BOOKID FOREIGN KEY(BOOK_ID)
REFERENCES BOOK_MASTER(BOOK_ID));

use library;

CREATE TABLE LIBRARY_INCHARGE_INFO(
INCHARGE_ID INT PRIMARY KEY,
INCHARGE_NAME VARCHAR(25),
INCHARGE_PASSWORD VARCHAR(15));

INSERT INTO LIBRARY_INCHARGE_INFO(INCHARGE_ID,INCHARGE_NAME,INCHARGE_PASSWORD)
VALUES(1,'TEJAS BELSARE','TEJ'),
(2,'PRASANNA','PRA'),
(3,'SHREYA','SHR');

SELECT * FROM LIBRARY_INCHARGE_INFO;
